resolver: lts-14.27
allow-newer: true
extra-deps:
# mu
- mu-schema-0.3.0.0
- mu-rpc-0.3.0.0
- mu-optics-0.3.0.0
- mu-avro-0.3.0.0
- mu-protobuf-0.3.0.0
- mu-grpc-client-0.3.0.0
- mu-grpc-server-0.3.0.0
- mu-grpc-common-0.3.0.0
- compendium-client-0.2.0.0
# dependencies of mu
- http2-client-0.9.0.0
- http2-client-grpc-0.8.0.0
- http2-grpc-types-0.5.0.0
- http2-grpc-proto3-wire-0.1.0.0
- warp-grpc-0.4.0.1
- proto3-wire-1.1.0
- language-protobuf-1.0.1
- language-avro-0.1.3.1
- avro-0.5.1.0
- HasBigDecimal-0.1.1
- optics-core-0.2
- indexed-profunctors-0.1
