# TODO update this file when mu-haskell is released
#resolver: lts-15.5
#allow-newer: true
#extra-deps:
## mu
#- mu-schema-0.3.1.0
#- mu-rpc-0.3.1.0
#- mu-optics-0.3.1.0
#- mu-avro-0.3.1.0
#- mu-protobuf-0.3.1.0
#- mu-grpc-client-0.3.1.0
#- mu-grpc-server-0.3.1.0
#- mu-grpc-common-0.3.1.0
#- compendium-client-0.2.0.0
## dependencies of mu
#- http2-client-0.9.0.0
#- http2-client-grpc-0.8.0.0
#- http2-grpc-proto3-wire-0.1.0.0
#- http2-grpc-types-0.5.0.0
#- proto3-wire-1.1.0
#- warp-grpc-0.4.0.1
#- hw-kafka-client-3.0.0
#- hw-kafka-conduit-2.6.0
#- git: https://github.com/hasura/graphql-parser-hs.git
#  commit: 1380495a7b3269b70a7ab3081d745a5f54171a9c
#- avro-0.5.1.0
#- language-avro-0.1.3.1

resolver: lts-15.5
allow-newer: true
extra-deps:
# mu
- git: https://github.com/higherkindness/mu-haskell.git
  commit: e4ec9802643d9a2e3da9c6964dddc1861368401a
  subdirs:
  - core/schema
  - core/rpc
  - core/optics
  - adapter/avro
  - adapter/protobuf
  - grpc/common
  - grpc/server
  - grpc/client
- compendium-client-0.2.0.0
# dependencies of mu
- http2-client-0.9.0.0
- http2-client-grpc-0.8.0.0
- http2-grpc-proto3-wire-0.1.0.0
- http2-grpc-types-0.5.0.0
- proto3-wire-1.1.0
- warp-grpc-0.4.0.1
- hw-kafka-client-3.0.0
- hw-kafka-conduit-2.6.0
- git: https://github.com/hasura/graphql-parser-hs.git
  commit: 1380495a7b3269b70a7ab3081d745a5f54171a9c
- avro-0.5.1.0
- language-avro-0.1.3.1
