language: scala

jdk:
- oraclejdk8

matrix:
  include:
    - scala: 2.10.6
      env:
        - SBT_VERSION=0.13.16
    - scala: 2.11.11
      env:
        - SBT_VERSION=0.13.16
    - scala: 2.12.3
      env:
        - SBT_VERSION=1.0.1

before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.sbt/cache
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.ivy2

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_80bb47bfd841_key -iv $encrypted_80bb47bfd841_iv -in secring.gpg.enc -out secring.gpg -d;
  fi

script:
- if [ "$TRAVIS_SCALA_VERSION" = "2.11.11" -o "$TRAVIS_SCALA_VERSION" = "2.12.3" ]; then
    sbt ++$TRAVIS_SCALA_VERSION orgScriptCI;
  fi
- sbt ^^$SBT_VERSION protogen/compile

after_success:
- if [ "$TRAVIS_SCALA_VERSION" = "2.11.11" -o "$TRAVIS_SCALA_VERSION" = "2.12.3" ]; then
    sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess;
  fi
- if [ "$TRAVIS_SCALA_VERSION" = "2.10.6" -o "$TRAVIS_SCALA_VERSION" = "2.12.3" ]; then
    if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      if grep -q "SNAPSHOT" version.sbt; then
        sbt ^^$SBT_VERSION protogen/publish;
      else
        if [ "$SBT_VERSION" = "1.0.1" ]; then
          git reset --hard HEAD;
          git clean -f;
          git checkout master;
          git pull origin master;
          sbt ^^$SBT_VERSION protogen/release;
        fi
      fi
    fi
  fi
- bash <(curl -s https://codecov.io/bash) -t 5b75b318-ab71-4fbc-9203-bfa7765cdbdc